CREATE TABLE HEADHUNTER (
HH_ID INT NOT NULL PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
TelNbr VARCHAR(20)
);

/* COMMIT WORK;*/

INSERT INTO HEADHUNTER VALUES (1, 'Hans Heads', '3235674389');
INSERT INTO HEADHUNTER VALUES (2, 'Lieve Seated', '32472345612');
INSERT INTO HEADHUNTER VALUES (3, 'Louis Wanderer', '3214567890');

CREATE TABLE ORGANISATION (
OrgName VARCHAR(30) NOT NULL PRIMARY KEY,
Sector VARCHAR(15),
Turnover INT
);

/* COMMIT WORK;*/

INSERT INTO ORGANISATION VALUES ('Travel Far', 'tourism', 300);
INSERT INTO ORGANISATION VALUES ('Fly Away', 'tourism', 740);
INSERT INTO ORGANISATION VALUES ('Table Ready', 'nutrition', 760);
INSERT INTO ORGANISATION VALUES ('Devos Dankers', 'nutrition', 1780);
INSERT INTO ORGANISATION VALUES ('Grain of Wheat', 'nutrition', 540);
INSERT INTO ORGANISATION VALUES ('Bioconstruct', 'construction', 460);

CREATE TABLE HEADHUNTER_ORG (
OrgName VARCHAR(30) NOT NULL REFERENCES ORGANISATION(OrgName),
HH_ID INT NOT NULL REFERENCES HEADHUNTER(HH_ID),
PRIMARY KEY (ORGName, HH_ID)
);

/* COMMIT WORK;*/

INSERT INTO HEADHUNTER_ORG VALUES ('Travel Far', 1);
INSERT INTO HEADHUNTER_ORG VALUES ('Fly Away', 1);
INSERT INTO HEADHUNTER_ORG VALUES ('Table Ready', 1);
INSERT INTO HEADHUNTER_ORG VALUES ('Devos Dankers', 2);
INSERT INTO HEADHUNTER_ORG VALUES ('Grain of Wheat', 2);
INSERT INTO HEADHUNTER_ORG VALUES ('Table Ready', 2);
INSERT INTO HEADHUNTER_ORG VALUES ('Bioconstruct', 3);
/* COMMIT WORK;*/